### PR TITLE
do not import mock, include tests in tarball

### LINKED ISSUE #7: tests in pypi tarball + unittest.mock
Hi,

could you please consider to ship tests in release tarball? Also, you could eventually replace mock with built-in unittest.mock.

### PR DESCRIPTION
**Pull request by pgajdos**
Fixes #7. Not completely sure about MANIFEST.in, I have little experience here.

### CODE REVIEW

**Comment by dkarchmer** [comment]
Can you explain why you need this change? What do you need tests to be part of the installation package?
I am not sure changing `MANIFEST.in` is enough as I think you also need to change `setup.py` but you are forcing everybody to get the tests for no clear reason. Is this a common thing for packages to do?

**Comment by dkarchmer** [comment]
But still trying to understand the goal. You want to be able to re-test the package after you install it (after you do `pip install`). I guess the only reason to do this would be to double check what the package builders should do.

I do accept that I have not had time to add testing to the CI process, so it depends on me testing before I release, but I did not know people want to keep retesting a package that was publicly released. I for sure don't want to be re-testing Django myself, and trust that the Django team tested the package before releasing.

Anyway, I don't think this change does anything other than removing `mock` so if you wanted to add testing to the package, you have not done so. I will investigate at some point and see if I can find a good example for a simple package I can borrow from

**Comment by dkarchmer** [comment]
From a quick scan, I don't see djangorestframework or djangorestfrmework-simplejwt (https://github.com/jazzband/djangorestframework-simplejwt) including tests in the installation. In fact, they very explicitly exclude them.

Sorry, but I don't think I am going to accept a PR for this until I am pointed to a GitHub repo for a simple package that does this

**Comment by pgajdos** [comment]
Yep, as I have written in my first comment, I am not sure about the part that includes tests and I do not know how to test. Let's close this.

**Pull request closed without merging**
